name: Update Profile

on:
  schedule:
    - cron: "*/60 * * * *"   # every 60 minutes; tune as you like
  workflow_dispatch: {}
  repository_dispatch:       # for external triggers (e.g., WordPress webhook)
    types: [wp-post-published, li-newsletter-published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests PyYAML

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: personal token if you need cross-repo/org read
          GH_PAT: ${{ secrets.GH_PAT }}
          # Your config (edit these)
          WORDPRESS_FEED: "https://www.woodruff.dev/category/blog/feed/"
          GITHUB_USER: "cwoodruff"
          # Comma-separated list of repos to watch for releases, or leave blank to scan user’s repos
          RELEASE_REPOS: "cwoodruff/morespeakers-com,cwoodruff/chinook-razor-htmx, cwoodruff/genetic-algorithms"
          # LinkedIn workaround: RSS feed or webhook JSON URL (see section 4)
          LINKEDIN_RSS: "https://rss.app/feeds/innzFN2UEgc4pUUR.xml"
          LINKEDIN_WEBHOOK_CACHE: ""
          ITEMS_PER_SECTION: "10"
        run: |
          python scripts/update_readme.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: refresh profile sections"
            git push
          else
            echo "No changes."
          fi
